# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be623698bb08e8732dc6a40b4c7065cd38dbdecea35548e2f84d8b9bc1fae7be10028b9034abd361ca2a5e298be585be205bcb3590e8e570aa055a2d557e695d

test:
  secret_key_base: b6236da137feb079721802660bdb82906a6b684d82060a7d156e8e28cd358cde47abd3a4e09a659dd78674bf8d12e74e5a57afd864769f136848b179482d214a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
